# .github/workflows/build-windows-exe.yml
name: Build Windows EXE
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt
      - name: Build exe
        run: |
          pyinstaller --onefile --windowed --icon app.ico ^
            --add-data "assets;assets" src/your_script.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-windows-exe
          path: dist/*.exe
